# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  create:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  beat:

    strategy:
      matrix:
        arch: [armv7]
        beat: [filebeat, metricbeat, packetbeat, heartbeat]

    runs-on: ubuntu-latest
    container:
      image: golang:1.20.11

    name: ${{ matrix.beat }} ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

      - name: Set tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build beat (on arch)
        id: build-beat
        with:
          arch: ${{ matrix.arch }}
          githubToken: ${{ github.token }}
          run: |
            ./build.sh ${{ matrix.beat }} ${{ matrix.arch }} ${{ steps.vars.outputs.tag }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.beat }}-${{ matrix.arch }}
          path: ${{ matrix.beat }}-*.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.beat }}-*.tar.gz

